name: Publish to CurseForge

#on:
#  push:
#    tags:
#      - '**'
#    branches: [ master ]
#  pull_request:
#    tags:
#      - '**'
#    branches: [ master ]

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: alpha, beta, or release
        default: alpha

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
      ARCHIVE: HandyNotes-Achievements.zip
      TOC: HandyNotes_Achievements.toc
      CHANGELOG_TYPE: markdown

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: toolchain
        run: |
          #sudo apt-get -y update
          sudo apt-get -y install jq

      # disregard specific commit hash, and honor .gitmodule branch
      - name: update
        run: make update

      - name: archive
        run: make archive

      - name: upload_curseforge
        run: make upload_curseforge

# TODO parse upload status
# TODO fail on redundant version + release type combo?
# TODO or overwrite redundant version + release type combo?
# TODO or auto subminor version bump?
# TODO run on push of new tag


